### ISSUE TITLE
"ckeditor:install": "symfony-cmd", in composer.json gives error 

### ISSUE THREAD

**Issue by fazliddin** [javiereguiluz/easy-admin-demo#100]
```
Script ckeditor:install returned with error code 1
!!  
!!                                                                
!!    There are no commands defined in the "ckeditor" namespace.  
!!                                                                
!!  
!!  
Script @auto-scripts was called via post-update-cmd

**Comment by ganti** [comment]
i could fix it with `composer require friendsofsymfony/ckeditor-bundle`

**Comment by ganti** [comment]
i could fix it with:

```bash
composer require symfony/yaml
composer require friendsofsymfony/ckeditor-bundle
composer install
```

**Comment by AymLaf** [comment]
I wasnt able to fix it with composer require commands mentionned above because each one needs the other one.
I had to add the package directly inside the composer.json like that (inside the require part) :

        "symfony/yaml": "*",
        "friendsofsymfony/ckeditor-bundle": "*"

**Comment by AntonioCS** [comment]
This error is still present!

**Comment by javiereguiluz** [comment]
Thanks for creating this issue. However, we must close it because we're discontinuing this project and archiving this repository in favor of the new EasyAdmin Demo project.

More details: https://easycorp.github.io/blog/posts/a-new-easyadmin-demo-application
