### ISSUE TITLE
ImageField handling FileNotFoundException

### ISSUE THREAD

**Issue by mingyuen78** [javiereguiluz/easy-admin-demo#103]
How do we handle the error in CrudController, under method configureFields(string $pageName) 

I have an ImageField, scenario is that supposedly the file uploaded gone missing. (someone accidentally deleted / renamed that file)

I get hit with the error FileNotFoundException.

**Comment by javiereguiluz** [comment]
Thanks for creating this issue. However, we must close it because we're discontinuing this project and archiving this repository in favor of the new EasyAdmin Demo project.

More details: https://easycorp.github.io/blog/posts/a-new-easyadmin-demo-application
