### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by acantepie** [javiereguiluz/easy-admin-demo#105]
What i have done :
`git clone https://github.com/javiereguiluz/easy-admin-demo`
`cd easy-admin-demo/`

`composer install` => KO

Got following error:
```
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - ocramius/package-versions is locked to version 1.4.2 and an update of this package was not requested.
    - ocramius/package-versions 1.4.2 requires composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - ocramius/package-versions 1.4.2 requires composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - doctrine/orm v2.7.3 requires ocramius/package-versions ^1.2 -> satisfiable by ocramius/package-versions[1.4.2].
    - doctrine/orm is locked to version v2.7.3 and an update of this package was not requested.

ocramius/package-versions only provides support for Composer 2 in 1.8+, which requires PHP 7.4.
```
To fix this error :
`rm composer.lock`

remove `"ckeditor:install": "symfony-cmd",`line on composer.json
`composer update`

Composer update will fail, because `symfony/yaml`dependency is missing, so i have to install it:
`composer require symfony/yaml`

**Comment by Fredkiss3** [comment]
You should just install `symfony/yaml` and remove ckeditor, it works fine

**Comment by javiereguiluz** [comment]
Thanks for creating this issue. However, we must close it because we're discontinuing this project and archiving this repository in favor of the new EasyAdmin Demo project.

More details: https://easycorp.github.io/blog/posts/a-new-easyadmin-demo-application
