### ISSUE TITLE
Problem trying to upload product photo

### ISSUE THREAD

**Issue by ReynerHL** [javiereguiluz/easy-admin-demo#16]
The main problem is that it is trying to create a new folder with "products" as identifier, but the folder "product" (without ending s) already exist.
Diging into the config file, in the vich_uploader section, we note a little typo and changing "products" by "product" solved the problem.
Hope this helps. And congratulation for the great example.

**Comment by javiereguiluz** [comment]
Thanks for reporting this issue. I've fixed it in #19.
