### ISSUE TITLE
Problem trying to access root url

### ISSUE THREAD

**Issue by ReynerHL** [javiereguiluz/easy-admin-demo#17]
In the **app/config/routing.yml** file, the "_homepage" route definition does not work. I guess it should redirect to the **"easyadmin"** (this one already exists) route instead **"admin"**.
Hope this help

**Comment by javiereguiluz** [comment]
Both routes should work (`admin` is the deprecated one) but you are absolutely right and `easyadmin` should be used because it's the recommended one. I've changed it in #20.
