### ISSUE TITLE
Warning while loading fixtures

### ISSUE THREAD

**Issue by jazithedev** [javiereguiluz/easy-admin-demo#26]
While using this in my console:
`php bin/console doctrine:fixtures:load --append`

I'm getting the following warning:

```
A:\xampp\htdocs\easy-admin-demo>php bin/console doctrine:fixtures:load --append
  > loading [10] AppBundle\DataFixtures\ORM\LoadUsers
  > loading [20] AppBundle\DataFixtures\ORM\LoadCategories
  > loading [50] AppBundle\DataFixtures\ORM\LoadProducts


  [Symfony\Component\Debug\Exception\ContextErrorException]
  Warning: mt_rand(): max(-727379969) is smaller than min(1215752192)


doctrine:fixtures:load [--fixtures [FIXTURES]] [--append] [--em EM] [--shard SHARD] [--purge-with-truncate] [--multiple-transactions] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>`
```

Windows 10, PHP 5.6

After going trough the rest of commands, I'm running server and can't login to admin part of the demo.

>  Invalid credentials. 

And one more question. Where is the whole config for EasyAdmin in this demo ?

**Comment by acamilleri** [comment]
It's maybe a bug in PHP 5.6, https://bugs.php.net/bug.php?id=64450&edit=1

I've got the same problem with PHP 5.6.16 but i'm testing with PHP 7.0.0 and no problem ;)

**Comment by javiereguiluz** [comment]
I'm afraid that I cannot reproduce this error. I'm using PHP 5.6 and it works as expected:

![easyadmin-demo](https://cloud.githubusercontent.com/assets/73419/14586578/5c933c54-049d-11e6-9ed4-d36e975317fb.png)

**Comment by jazithedev** [comment]
PHP **5.6.15** here. Maybe it's the difference causing the problem. Server placed on **XAMPP v3.2.2** for Windows.

```
PHP 5.6.15 (cli) (built: Oct 29 2015 12:40:36)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

**Comment by javiereguiluz** [comment]
But I updated to 5.6.19 very recently. I was using 5.6.10 or something like that before and I couldn't reproduce it either 😕

**Comment by jazithedev** [comment]
Damn, have no idea then :disappointed:. Maybe there was indeed a bug just between those versions (5.6.10 < x < 5.6.19)?

**Comment by javiereguiluz** [comment]
I've pushed a change in 5561724. @ktrzos could you please check if this fix the problem? Thanks!

**Comment by jazithedev** [comment]
Problem solved ;). It's working now. Thanks for Your time!
