### ISSUE TITLE
Example for min/max value for number form fields

### ISSUE THREAD

**Issue by aschmidt1976** [javiereguiluz/easy-admin-demo#27]
Hi,

I'm trying to define a property "http_status" where input values are restricted to a range of 200-530 (HTTP status codes).
I created an annotation for the column in the entity class:
`
    /**
     * @var integer
     * @ORM\Column(name="http_status", type="smallint", nullable=true)
     * @Assert\Range(
     *      min = 200,
     *      max = 530,
     *      minMessage = "HTTP status code must be at least 200.",
     *      maxMessage = "HTTP status code must not exceed 530."
     * )
     */
`
But I have no idea how to create a definition for this in EasyAdminBundle. Whatever I do, no "min" and/or "max" attribute will be added to the input field.

Could you please create an example in a future version?

A possible showcase would be restricting purchases to persons aged 18 or older.

Thank you!

**Comment by aschmidt1976** [comment]
I closed the issue because I found the solution:
`- { property: 'http_status', label: 'HTTP status', type: 'integer', type_options: { attr: { value: '', min: 200, max: 530 } } }`

**Comment by mtazi9** [comment]
Your solution is not working for me !

**Comment by indapublic** [comment]
I have easyadmin 2.3.5 and `type_options: { attr: { value: '', min: 200, max: 530 } }` works
