### ISSUE TITLE
Integer issue on Search

### ISSUE THREAD

**Issue by ghost** [javiereguiluz/easy-admin-demo#34]
Hello, 
if I try to put on the search label an string only with numbers like 92611125088891231131 the sistem give an error in attached.
![image](https://cloud.githubusercontent.com/assets/16149868/21652354/a3f68104-d2ac-11e6-8986-0de849eeb9fc.png)

![image](https://cloud.githubusercontent.com/assets/16149868/21652389/befa5fa2-d2ac-11e6-85a5-b881c54384ee.png)

Is therre a possible solution?

Thank you

**Comment by javiereguiluz** [comment]
Closing as fixed in the latest versions of the bundle:

![search-numbers](https://user-images.githubusercontent.com/73419/31400589-6f92f94a-adf0-11e7-808d-fb0b8b5f3cd3.png)
