### ISSUE TITLE
The child node "from_email" at path "fos_user" must be configured

### ISSUE THREAD

**Issue by Kvartir54** [javiereguiluz/easy-admin-demo#37]
Following this https://github.com/javiereguiluz/easy-admin-demo#how-to-install-this-project

"composer install" - doesn't work (as described in this issue https://github.com/javiereguiluz/easy-admin-demo/issues/36)

use "compose update" and got error "The child node "from_email" at path "fos_user" must be configured"

if insert something like this into "config.yml" in "fos_user" section
from_email:
        address:        domain@example.com
        sender_name:    Demo App

then everything is good

Please, change description "how-to-install-this-project" if needed

**Comment by stollr** [comment]
This has been fixed already in 9a842405072a9940e67757f69dfc60b7aa811e06

**Comment by Mar0z** [comment]
1. I'm getting "The child node "from_email" at path "fos_user" must be configured"
2. After adding: from_email:
                         address: "no-reply@domain.com"
                         sender_name: "no-reply"
   without quotes, with single or double quotes.
3.Geting: The file ../..config.yml does not contain valid YAML in ../../config.yml (which is being imported from ../../config_dev.yml).

What I am missing?
