### ISSUE TITLE
Mix between images with same name

### ISSUE THREAD

**Issue by ipesanz** [javiereguiluz/easy-admin-demo#41]
If you create different new products with different photos coming from your PC with the same name
example: index.png (size = 142Kb) & index.png (size = 76Kb)

As the Entity "Product" takes only a reference (name of photo file) to a folder (web/uploads/images/products) where is supposed to exist a file with that name, it can exist only one photo with the given name
reality: product1 & product2 will have last index.png of size 76Kb because first photo was overwritten

Also, if you delete/change name of photo; a broken link image is showed

**Which would be the best way to change this behaviour?**

**Comment by javiereguiluz** [comment]
Closing this old issue because it's probably no longer relevant after the upgrade done in #71. Sorry we didn't reply on time.
