### ISSUE TITLE
There are no commands defined in the "server" namespace.

### ISSUE THREAD

**Issue by stollr** [javiereguiluz/easy-admin-demo#45]
When I execute the command `php bin/console server:run` as described in the readme, I do get the following error with Symfony 3.3:

> [Symfony\Component\Console\Exception\CommandNotFoundException]  
> There are no commands defined in the "server" namespace. 

To fix the error one has to register the *WebServerBundle* in `AppKernel.php` (see https://stackoverflow.com/a/43119148/1119601),

**Comment by stollr** [comment]
I'll create a PR to fix this issue.

**Comment by javiereguiluz** [comment]
Fixed by #46. Thanks for reporting this and for fixing it!
