### ISSUE TITLE
The child node "from_email" at path "fos_user" must be configured

### ISSUE THREAD

**Issue by Mar0z** [javiereguiluz/easy-admin-demo#51]
Appologies for reopening issue but i still have this problem.

1. I'm getting "The child node "from_email" at path "fos_user" must be configured"
2. After adding: from_email:
                         address: "no-reply@domain.com"
                         sender_name: "no-reply"
Tried without quotes, with single or double quotes.
3.Geting: The file ../..config.yml does not contain valid YAML in ../../config.yml (which is being imported from ../../config_dev.yml).
What I am missing?

**Comment by javiereguiluz** [comment]
Closing this old issue because it's probably no longer relevant after the upgrade done in #71. Sorry we didn't reply on time.
