### ISSUE TITLE
Installation /app folder missing

### ISSUE THREAD

**Issue by madmax76** [javiereguiluz/easy-admin-demo#56]
Hi,

Error from GUI:
The configured class "App\Entity\Product" for the path "easy_admin.entities.Product" does not exist. Did you forget to create the entity class or to define its namespace?

$ ls -a
.			.gitignore		composer.json		src			vendor
..			.travis.yml		composer.lock		templates
.env			LICENSE			config			tests
.env.dist		README.md		phpunit.xml.dist	translations
.git			bin			public			var

Environment:

OSX10.12.6
PHP: 7.1.11
Zend Engine: v3.1.0

Steps:
composer create-project symfony/framework-standard-edition max "3.3.*"
cd max
1. composer create-project "symfony/skeleton:^3.3" demo
2. cd demo
3. composer require admin
4. vi config/packages/doctrine.yaml

change:        url: '%env(resolve:DATABASE_URL)%'
to:                 url: '%env(DATABASE_URL)%'

5. composer require symfony/web-server-bundle

6. vi : config/routes.yml
ADD>>>
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

Anything obvious I am missing?

Cheers,
Max

**Comment by unclexo** [comment]
"app" folder is missing here too!

**Comment by m6t9** [comment]
I support, it is not clear.

**Comment by marcmorente** [comment]
"app" folder is missing !!!!!

**Comment by Deveosys** [comment]
Same here ;)

**Comment by KarthikRao123** [comment]
i downloaded project form git but app folder is missing in that file

**Comment by scorpioniz** [comment]
Where is the parameters.yml file?? it does not exists in entire project

**Comment by kumarsujendra** [comment]
No file available app/config/parameters.yml

**Comment by javiereguiluz** [comment]
Closing this old issue because it's probably no longer relevant after the upgrade done in #71. Sorry we didn't reply on time.
