### ISSUE TITLE
List prerequisites on README file

### ISSUE THREAD

**Issue by karousn** [javiereguiluz/easy-admin-demo#58]
I try to install the demo i got this error :
`HP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /var/www/html/easy-admin-demo/src/Kernel.php:25`

I use PHP 7.0.19-1

**Comment by anybug** [comment]
same here with PHP 7.0.27-1~dotdeb+8.1 
did you figure it out ?

**Comment by anybug** [comment]
actually it does work with PHP7.1 and Symfony 4. However, as i'm not familiar yet with SF4, i also managed to make it work with PHP7.0 by downloading Symfony3 version from branch called "symfony3.3"

**Comment by javiereguiluz** [comment]
Closing this old issue because it's probably no longer relevant after the upgrade done in #71. Sorry we didn't reply on time.
