### ISSUE TITLE
Impossible to edit a Product : input Image is mandatory

### ISSUE THREAD

**Issue by Rebolon** [javiereguiluz/easy-admin-demo#61]
I'm testing this demo project and i get an error when i try to edit a product.

Click on a product item : http://localhost:8001/admin/?action=edit&entity=Product&menuIndex=0&submenuIndex=0&sortField=createdAt&sortDirection=DESC&page=1&referer=%252Fadmin%252F%253Faction%253Dlist%2526entity%253DProduct%2526menuIndex%253D0%2526submenuIndex%253D0%2526sortField%253DcreatedAt%2526sortDirection%253DDESC%2526page%253D1&id=1

Change the title

Click on submit

Expected : The item is saved with the new title

Get : Warning on input Image because it need one (even if we don't want to change it)

**Comment by javiereguiluz** [comment]
Closing this old issue because it's probably no longer relevant after the upgrade done in #71. Sorry we didn't reply on time.
