### ISSUE TITLE
Workaround to PHP 7.0 (not allowed visibility on const variables)

### ISSUE THREAD

**Issue by joserprieto** [javiereguiluz/easy-admin-demo#66]
On file:

./src/Kernel.php
```php
class Kernel extends BaseKernel
{
    use MicroKernelTrait;

    private const CONFIG_EXTS = '.{php,xml,yaml,yml}';
```
This isn't allowed on PHP < 7.1

For example: [](https://knpuniversity.com/screencast/php7/private-constants)

So, a "workaround" will be:

```php
class Kernel extends BaseKernel
{
    use MicroKernelTrait;

    /** 
     * Only PHP > 7.1:
     * private const CONFIG_EXTS = '.{php,xml,yaml,yml}';
     */
    const CONFIG_EXTS = '.{php,xml,yaml,yml}';
```

Regards.

**Comment by joserprieto** [comment]
May be most useful the PR #62 

Regards.

**Comment by javiereguiluz** [comment]
Sorry for not replying earlier. We updated this project to the latest Symfony version and bumped PHP requirements, so this is no longer needed. Sorry.
