### ISSUE TITLE
Cannot submit edit product form without selecting an image file

### ISSUE THREAD

**Issue by brooksvb** [javiereguiluz/easy-admin-demo#75]
Form will not allow you to submit because the field is required, regardless of if you intend to change the image or not.

**Comment by parijke** [comment]
Version with EA3 throws an error while adding a product
```
HTTP 500 Internal Server Error
An exception occurred while executing 'INSERT INTO product (created_at, tags, ean, enabled, image, features, price, name, description) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["2020-07-01 12:46:00", "a", "1212", 1, null, "a:1:{i:1;s:1:\"a\";}", 1, "Test", "Test product"]:

SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: product.image
```

But it is not possible to add an image on the form

**Comment by javiereguiluz** [comment]
Thanks for creating this issues. However, we must close it because we're discontinuing this project and archiving this repository in favor of the new EasyAdmin Demo project.

More details: https://easycorp.github.io/blog/posts/a-new-easyadmin-demo-application
