### ISSUE TITLE
Doesnt work with PHP 7.4

### ISSUE THREAD

**Issue by rileyrg** [javiereguiluz/easy-admin-demo#78]
Notice: Trying to access array offset on value of type null in /home/rgr/Dropbox/homefiles/development/Symfony/easy-admin-demo/config/routes/../../src/Controller/ (which is being imported from "/home/rgr/Dropbox/homefiles/development/Symfony/easy-admin-demo/config/routes/annotations.yaml"). Make sure annotations are installed and enabled.

Setting my system PHP to 7.3 and it worked.

I could then revert to PHP 7.4 (update-alternatives) and it continued to work.

**Comment by featuriz** [comment]
Same error in PHP7.4.
How do you solved?

**Comment by garak** [comment]
I had the same problem, solved by requiring Symfony 4.4 instead of 4.3.
You just need to change it in composer.json

**Comment by rendyep** [comment]
Installing Symfony 4.4 by updating composer.json of `extra` node from
```
"extra": {
        "symfony": {
            "allow-contrib": true,
            "require": "4.3.*"
        }
    }
```

to 
```
"extra": {
        "symfony": {
            "allow-contrib": true,
            "require": "4.4.*"
        }
    }
```

and running `composer update` does work.

**Comment by javiereguiluz** [comment]
Thanks for creating this issues. However, we must close it because we're discontinuing this project and archiving this repository in favor of the new EasyAdmin Demo project.

More details: https://easycorp.github.io/blog/posts/a-new-easyadmin-demo-application
