### ISSUE TITLE
Datetime search doesn't work

### ISSUE THREAD

**Issue by Luvelnet** [javiereguiluz/easy-admin-demo#80]
Hello.

In my ListView of entity, when I search over datetime field, this is not included in query. 

I try included manually (but not result):

`search: 
          fields: ['fechaAlta','fechaVisto','fechaFirma']`

Thanks!

**Comment by javiereguiluz** [comment]
Thanks for creating this issues. However, we must close it because we're discontinuing this project and archiving this repository in favor of the new EasyAdmin Demo project.

More details: https://easycorp.github.io/blog/posts/a-new-easyadmin-demo-application
