### ISSUE TITLE
Error on Composer Install

### ISSUE THREAD

**Issue by ioniks** [javiereguiluz/easy-admin-demo#86]
Hi,

When i clone the repository and make
`composer install`

Error append :
` There are no commands defined in the "ckeditor" namespace.`

**Comment by tomazov** [comment]
same mistake PHP 7.4.7

> $ **composer install**
>
> Loading composer repositories with package information
> Installing dependencies (including require-dev) from lock file
> Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
> Nothing to install or update
> Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.
> Package zendframework/zend-eventmanager is abandoned, you should avoid using it. Use laminas/laminas-eventmanager instead.
> Generating autoload files
> 75 packages you are using are looking for funding.
> Use the `composer fund` command to find out more!
> ocramius/package-versions:  Generating version class...
> ocramius/package-versions: ...done generating version class
> Executing script ckeditor:install [KO]
>  [KO]
> Script ckeditor:install returned with error code 1
> !!
> !!
> !!    There are no commands defined in the "ckeditor" namespace.
> !!
> !!
> !!
> Script @auto-scripts was called via post-install-cmd

**Comment by ruibaby** [comment]
same error in PHP 7.3.11

**Comment by glls** [comment]
remove the line 
`"ckeditor:install": "symfony-cmd",`
from `package.json` and it will work

**Comment by j0r1s** [comment]
> remove the line
> `"ckeditor:install": "symfony-cmd",`
> from `package.json` and it will work

@glls probably meant `composer.json`

**Comment by ElGittoJunior** [comment]
same error in PHP 7.4.9

**Comment by rkeet** [comment]
Got this error too, the repo is missing: `friendsofsymfony/ckeditor-bundle`. 

After getting the error (or add it to the `composer.json` file yourself) run: 

```
composer require friendsofsymfony/ckeditor-bundle
```

**Comment by MagePsycho** [comment]
Why this issue is still not resolved?
> Script ckeditor:install returned with error code 1

**Comment by javiereguiluz** [comment]
Thanks for creating this issues. However, we must close it because we're discontinuing this project and archiving this repository in favor of the new EasyAdmin Demo project.

More details: https://easycorp.github.io/blog/posts/a-new-easyadmin-demo-application
