### ISSUE TITLE
Feature Request: Add edgy Use Cases to show EA's full potential

### ISSUE THREAD

**Issue by parijke** [javiereguiluz/easy-admin-demo#87]
Although EA demo is a nicely done demo, it does not demonstrate all posibilities of EA. Ie CollectionField is used nowhere, while this is a frequently used Use Case (ie create Tasks on a Project or InvoiceItems on an Invoice.

It would be great if these kind of use cases could be shown within the demo as well.

**Comment by javiereguiluz** [comment]
Thanks for creating this issue. However, we must close it because we're discontinuing this project and archiving this repository in favor of the new EasyAdmin Demo project.

More details: https://easycorp.github.io/blog/posts/a-new-easyadmin-demo-application
