### ISSUE TITLE
Add a login page & security related examples

### ISSUE THREAD

**Issue by ogizanagi** [javiereguiluz/easy-admin-demo#9]
Now that EasyAdmin is more & more sophisticated (in the good sense of it) & powerful, maybe we can add some security related stuff to the demo ?

I'm thinking about:
- [x] A login page (with different users available in fixtures). We can use the Admin LTE login page.
- [x] A login/logout item in the menu sidebar or top navbar dropdown.
- [ ] Investigate how we can deal the best for roles management:
  - [ ] Disallow to access some pages (access controls, listener, ... ?)
  - [ ] Hide some elements in the menu according to roles (layout override, feature, allow extra keys in easyadmin config, ... ?).
- ...

**Comment by simonberton** [comment]
FOSUSERBUNDLE could work. I have one with the proper configuration on firewall so users with certains roles can access /admin/ where i then have easy admin

**Comment by javiereguiluz** [comment]
Closing it as fixed by #25, which integrated FOSUserBundle.
