### ISSUE TITLE
After install the demo i got this error 

### ISSUE THREAD

**Issue by figuitiko** [javiereguiluz/easy-admin-demo#92]
Return value of EasyCorp\Bundle\EasyAdminBundle\Factory\AdminContextFactory::getUser() must implement interface Symfony\Component\Security\Core\User\UserInterface or be null, instance of App\Entity\User returned

![image](https://user-images.githubusercontent.com/16547231/93009015-3f2fd480-f541-11ea-929b-8d62f901b1ef.png)

**Comment by disembarkedone** [comment]
this PR https://github.com/javiereguiluz/easy-admin-demo/pull/85 should solve your issue

It really should be merged with master

**Comment by javiereguiluz** [comment]
Thanks for creating this issue. However, we must close it because we're discontinuing this project and archiving this repository in favor of the new EasyAdmin Demo project.

More details: https://easycorp.github.io/blog/posts/a-new-easyadmin-demo-application
