### ISSUE TITLE
After install the demo i got this error

### ISSUE THREAD

**Issue by aldaelvis** [javiereguiluz/easy-admin-demo#93]
Argument 2 passed to Symfony\Component\Intl\NumberFormatter\NumberFormatter::setAttribute() must be of the type int, null given, called in D:\Proyectos\easy-admin-demo\vendor\easycorp\easyadmin-bundle\src\Intl\IntlFormatter.php on line 259

**Comment by javiereguiluz** [comment]
Thanks for creating this issue. However, we must close it because we're discontinuing this project and archiving this repository in favor of the new EasyAdmin Demo project.

More details: https://easycorp.github.io/blog/posts/a-new-easyadmin-demo-application
