### ISSUE TITLE
purchased quantity AND PurchaseItemCrudController

### ISSUE THREAD

**Issue by skianter** [javiereguiluz/easy-admin-demo#94]
How to specify item quantity and save in purchas_item?
Where and how does PurchaseItemCrudController get used?
Sorry for my (I know) stupid questions, but I'm new to this and I'm trying to find out how to use in a situazione where there's a association table (where I don't use ManyToMany because there'are other fields too).
Thank

**Comment by javiereguiluz** [comment]
Thanks for creating this issue. However, we must close it because we're discontinuing this project and archiving this repository in favor of the new EasyAdmin Demo project.

More details: https://easycorp.github.io/blog/posts/a-new-easyadmin-demo-application
