### ISSUE TITLE
purchaseItems not saved

### ISSUE THREAD

**Issue by skianter** [javiereguiluz/easy-admin-demo#95]
when editing a purchase, items are not saved.
That's important for me because I'm trying to save data with an association class (not a pure manyToMany, but a new association entity) and I need a working example, but there isn't at the moment.

**Comment by javiereguiluz** [comment]
Thanks for creating this issue. However, we must close it because we're discontinuing this project and archiving this repository in favor of the new EasyAdmin Demo project.

More details: https://easycorp.github.io/blog/posts/a-new-easyadmin-demo-application
