### ISSUE TITLE
App\DataFixtures\LoadCategories

### ISSUE THREAD

**Issue by lxregistry** [javiereguiluz/easy-admin-demo#98]
Warning: Uncaught ReflectionException: Class "Doctrine\Common\Persistence\ObjectManager" not found while loading "App\DataFixtures\LoadCategories" 

```
- use Doctrine\Common\Persistence\ObjectManager;

+ use Doctrine\Persistence\ObjectManager;
```

**Comment by javiereguiluz** [comment]
Thanks for creating this issue. However, we must close it because we're discontinuing this project and archiving this repository in favor of the new EasyAdmin Demo project.

More details: https://easycorp.github.io/blog/posts/a-new-easyadmin-demo-application
