### ISSUE TITLE
"symfony/yaml": "*" missing in composer.json

### ISSUE THREAD

**Issue by fazliddin** [javiereguiluz/easy-admin-demo#99]

**Comment by AntonioCS** [comment]
This error is still present.
Quick fix:
```
composer require yaml
```

**Comment by javiereguiluz** [comment]
Thanks for creating this issue. However, we must close it because we're discontinuing this project and archiving this repository in favor of the new EasyAdmin Demo project.

More details: https://easycorp.github.io/blog/posts/a-new-easyadmin-demo-application
